### PR TITLE
proposed backend integration

### PR DESCRIPTION
**Pull request by adisa39**
for seller-item screen for your review
 services/api.js created for API endpoint implementation

### CODE REVIEW

**Comment by swoocn** [comment]
Hi @adisa39 - 
Could you please resolve the build failure first?

image

**Comment by swoocn** [comment]
Well done @adisa39! 
Thank you for redoing the **Add/ Edit Seller Registration** screen.
Could you please replace the 'Search Center' field with 'Seller Type'?  Thx!
[See below for the finalized UX design for the screen]

image

**Comment by swoocn** [comment]
I went ahead and cleaned up some unused files @adisa39.  Any chance you could tidy up the component/ structure for the seller-registration?  Perhaps get rid of the /add-edit-seller package from components and make it more consistent with the rest..?

**Comment by omotoshoayomikun** [comment]
In Next.js 14, it is recommended to use fetch with async/await for caching, revalidating, and optimizing data fetching. By default, Next.js caches response data to improve performance. However, in cases where the data changes frequently and you don't want it to be cached, Next.js provides options within fetch to control caching behavior.

For example, to force caching, you can use:

const res = await fetch('apiurl', { cache: "force-cache" });

If you don't want to cache the response data at all, you can use:

const res = await fetch('apiurl', { cache: "no-store" });

For more details You can refer to the Next.js data fetching documentation. https://nextjs.org/docs/app/building-your-application/data-fetching/fetching-caching-and-revalidating

**Comment by swoocn** [comment]
This PR is superseded by https://github.com/map-of-pi/map-of-pi-frontend-react/pull/76.

**Pull request closed without merging**
