### PR TITLE
updated seller registration and user settings

### PR DESCRIPTION
**Pull request by adisa39**
sell center coordinate and user search center coordinates are included and handled at the backend.

### CODE REVIEW

**Review by DarinHajou — APPROVED** [review]
I see that you have moved away from using LocalStorage for sellCenter which solid, but it seems that the implementation is incomplete as sellCenter isn't being referenced in the handleSave function.

**Review by swoocn — CHANGES_REQUESTED** [review]
Frontend <-> Backend Integration will fail; see backend PR comments.  Thanks!

**Comment by swoocn** [comment]
Hi @adisa39!
Just a quick update— Darin and I had a conversation this morning, and he will be removing the mapCenterSchema and instead rely on the search_map_center and sell_map_center properties in the userSettings and sellerSchema types, respectively. Once those changes are merged, I'll revisit this PR accordingly. Sorry for the confusion and thanks for your patience!

**Comment by adisa39** [comment]
> I see that you have moved away from using LocalStorage for sellCenter which solid, but it seems that the implementation is incomplete as sellCenter isn't being referenced in the handleSave function.



> I see that you have moved away from using LocalStorage for sellCenter which solid, but it seems that the implementation is incomplete as sellCenter isn't being referenced in the handleSave function.

That is because it’s been handled at the backend

**Comment by adisa39** [comment]
> Hi @adisa39! Just a quick update— Darin and I had a conversation this morning, and he will be removing the mapCenterSchema and instead rely on the search_map_center and sell_map_center properties in the userSettings and sellerSchema types, respectively. Once those changes are merged, I'll revisit this PR accordingly. Sorry for the confusion and thanks for your patience!

Then how do youd deal with the default valu

**Pull request closed without merging**
