### PR TITLE
Worked on some issues relating to clickup issues column

### PR DESCRIPTION
**Pull request by omotoshoayomikun**
Worked on the following.
1. User pref, remove the “contact Map of Pi” menu option.
2. “Review face” graphic alignment needs correcting.
3. List of Reviews, reply buttons not displayed if reached from Buy from Seller screen.
4. React version, User Pref, Language: navigation after selection.

### CODE REVIEW

**Comment by swoocn** [comment]
I see what you're trying to do here, but we have yet to integrate the endpoint to make the rendering of the screen dynamic using the [id] param.  Given that we have frontend testing underway from the Solutions team, could we stabilize the Reviews screen either by mocking the [id] or wait till the integration is in place?  Thanks!

image

**Comment by swoocn** [comment]
> I see what you're trying to do here, but we have yet to integrate the endpoint to make the rendering of the screen dynamic using the [id] param. Given that we have frontend testing underway from the Solutions team, could we stabilize the Reviews screen either by mocking the [id] or wait till the integration is in place? Thanks!
> 
> image

Nevermind, I see you just forgot to mod the Review link in the sidebar nav component.  I'll get that fixed for you.

**Comment by swoocn** [comment]
@omotoshoayomikun - 

image

**Comment by swoocn** [comment]
> Worked on the following.
> 
> 1. User pref, remove the “contact Map of Pi” menu option. ✔
> 2. “Review face” graphic alignment needs correcting. ✔
> 3. List of Reviews, reply buttons not displayed if reached from Buy from Seller screen. ✔
> 4. React version, User Pref, Language: navigation after selection. ❌- _according to requirements, the User Preference sidebar nav screen should still stay open after language selection._

**Review by hollusam — APPROVED** [review]

**Comment by swoocn** [comment]
> > Worked on the following.
> > 
> > 1. User pref, remove the “contact Map of Pi” menu option. ✔
> > 2. “Review face” graphic alignment needs correcting. ✔
> > 3. List of Reviews, reply buttons not displayed if reached from Buy from Seller screen. ✔
> > 4. React version, User Pref, Language: navigation after selection. ❌- _according to requirements, the User Preference sidebar nav screen should still stay open after language selection._

_4. Will be revisited later due to involved implementation work with state management and higher priorities._

**Review by swoocn — APPROVED** [review]
Approved after being informed about the involved work and revisiting effort for Language Selection item.

**Pull request merged**
