### PR TITLE
Feature/connect lazy loading frontend to the backend endpoints

### PR DESCRIPTION
**Pull request by DarinHajou**

### CODE REVIEW

**Comment by DarinHajou** [comment]
Implement Lazy Loading Feature and Integrate Backend Endpoints.

Implements the lazy loading feature for map markers and integrates the frontend with backend endpoints. The map dynamically loads seller coordinates as the user interacts with the map (panning and zooming).

Issues Encountered:
- Backend is currently returning 500 errors, which affects data fetching.
- PI SDK causing initialization errors.

**Comment by swoocn** [comment]
GJ @DarinHajou!  Though, there is going to be quite a merge conflict between @DarinHajou and @adisa39 PRs since you both pretty much tackled the same files.  My plan will be to merge your PR after the active PR @ https://github.com/map-of-pi/map-of-pi-frontend-react/pull/97.  I will let you know accordingly.

**Comment by swoocn** [comment]
Please see my Discord DM.

**Review by swoocn — APPROVED** [review]
Great job with the lazy loading task for the frontend!  
We need to build the backend API to accommodate the origin and radius logic. Currently, you're calling the getSellers endpoint with optional params and getting back the same 10 sellers from the DB. 🙃

**Pull request merged**
