### PR TITLE
Worked on some issues

### PR DESCRIPTION
**Pull request by omotoshoayomikun**
- React version, User Pref, Photo: remove the phrase “One Photo Only”
- React version, User Pref, Language: navigation after selection
- “Review face” graphic alignment needs correcting
- Landing page: home&back buttons visible but greyed out
- philip@mapofpi.com as formal contact point… update app, TOS, Privacy Policy. 
- worked on the search buyer or item button on the home page

### CODE REVIEW

**Comment by swoocn** [comment]
> * React version, User Pref, Photo: remove the phrase “One Photo Only” ✔
> * React version, User Pref, Language: navigation after selection ❌
> * “Review face” graphic alignment needs correcting ✔
> * Landing page: home&back buttons visible but greyed out ❌- 
_User Preference screen the home/back buttons should be displayed as active buttons… enabling user to also tap them to exit Preference screen as well as the X button._ 
> * [philip@mapofpi.com](mailto:philip@mapofpi.com) as formal contact point… update app, TOS, Privacy Policy. ✔
> * worked on the search buyer or item button on the home page ✔

**Review by hollusam — APPROVED** [review]

**Comment by swoocn** [comment]
GJ @omotoshoayomikun - 
It appears the /seller/reviews/feedback link was broken so I went ahead and pushed a change to recover it.  Also, please revisit the ❌s when you can.  Thanks!

**Comment by omotoshoayomikun** [comment]
> GJ @omotoshoayomikun - It appears the /seller/reviews/feedback link was broken so I went ahead and pushed a change to recover it. Also, please revisit the ❌s when you can. Thanks!

@swoocn - the home&back buttons ought to be greyed out cause that's what am having on local development and I don't work on React version, User Pref, Language: navigation after selection because by default the when new language is selected it refresh the pages in some kind of  way so the state of the sidebar never to be stored probably in a local storage. I will look into it

**Comment by swoocn** [comment]
> @swoocn - the home&back buttons ought to be greyed out cause that's what am having on local development and I don't work on React version, User Pref, Language: navigation after selection because by default the when new language is selected it refresh the pages in some kind of way so the state of the sidebar never to be stored probably in a local storage. I will look into it

@omotoshoayomikun - Please note that the Home & Back buttons should be enabled when the User Preferences side bar navigation is opened.  This will allow users to leave the screen through various means.  

image

**Review by swoocn — APPROVED** [review]
LGTM!  Please note the 2nd requirement for the Home & Back navigation buttons item.  Thanks again and keep up the great work @omotoshoayomikun!

**Pull request merged**
